services:
  - type: web
    name: ytdlp-web-player
    runtime: image
    image:
      url: docker.io/matszwe02/ytdlp_web_player:latest
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "5000"
      - key: APP_TITLE
        value: YT-DLP Player
      - key: THEME_COLOR
        value: "#ff7300"
      - key: GENERATE_SPRITE_BELOW
        value: "1800"
      - key: AMOLED_BG
        value: "false"
      - key: MAX_VIDEO_AGE
        value: "3600"
    healthCheckPath: /
